---
- name: Deploy Docker Image of Calculator
  hosts: client1
  tasks:

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      shell: docker pull tejinder7/calculatordevops

    - name: Run Container
      shell: docker create -it tejinder7/calculatordevops
